# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/msm8974-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/msm8974-common

PRODUCT_COPY_FILES += \
    vendor/samsung/msm8974-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/msm8974-common/proprietary/vendor/firmware/a330_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pfp.fw \
    vendor/samsung/msm8974-common/proprietary/vendor/firmware/a330_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pm4.fw

PRODUCT_PACKAGES += \
    eglsubAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    flp.default \
    libC2D2 \
    libCB \
    libOpenCL \
    libadreno_utils \
    libbccQTI \
    libc2d30-a3xx \
    libflp \
    libgeofence \
    libgsl \
    libizat_core \
    liblbs_core \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_ds_api \
    libmmjpeg \
    libsc-a3xx \
    libscale \
    libstlport \
    libtime_genoff \
    libwvdrmengine \
    loc_launcher
